import Navbar from '@/components/navbar/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import getCurrentUser from './actions/getCurrentUser';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Try Blog',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col relative">
          <Navbar currentUser={currentUser} />
          <Image
            src={'/background.jpg'}
            alt="backgroundImage"
            width={1440}
            height={1024}
            className="static-background w-screen h-screen bg-gradient-to-br from-pink-200 via-transparent to-transparent bg-lightgray bg-center bg-cover"
          />
          <div className="absolute w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
